CREATE TABLE [dbo].[ListsCategory]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [CategoryId] INT NOT NULL DEFAULT 0,
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_ListCategory_ToUser] FOREIGN KEY (UserId) REFERENCES [User](Id)
)
